name: Hello workflow
# runs on an automatic trigger, whenever change is pushed to branch
on:  
  workflow_dispatch:
    inputs:
      environment:
        description: "This is the environment value where this workflow runs"
        default: "dev"
        required: true
        type: choice
        options:
            - dev
            - prod
            - staging
# this is name of the job
jobs:
  greet:
  # github runner, each job runs on runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello"

      - name: say hello to username
        run: echo "hello $USER"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: show what is the version of python, do
        

      
