# this is the name of the workflow that will be displayed in actions tab
name: cicd
# manual click (deliver) workflow when ever user needs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment value where this workflow runs
        default: "dev"
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
# every job need a runner, it is called parallaism

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "clone the code from github"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "docker container build"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "testing the container"

  deploy:
    if: inputs.environment == 'dev'
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploying the application
        run: echo "docker compose deployed the app"
        
