
name: Refactor CI/CD workflow with environment options

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "This is the environment value where this workflow runs"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello"

      - name: Say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: Show Python version
        run: python --version

      - name: Print selected environment
        run: echo "Environment selected is ${{ github.event.inputs.environment }}"





      
        

      
