# This will deploy the safe / secure/ tested app to the server.
name: Deploy To Server

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4            
              
            - name: ssh to prod server and create app folder
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.PROD_SERVER_HOST }}
                username: ${{ secrets.PROD_SERVER_USER }}
                key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                port: 22
                script: |
                    echo "Starting Deployment...."
                    mkdir -p devops

            - name: copy the docker-compose file
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.PROD_SERVER_HOST }}
                username: ${{ secrets.PROD_SERVER_USER }}
                key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                source: docker-compose.yml
                target: ~/devops 
                
            - name: ssh to prod server and run the app
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.PROD_SERVER_HOST }}
                username: ${{ secrets.PROD_SERVER_USER }}
                key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                port: 22
                script: |
                    echo "Running APP...."
                    sudo apt-get install docker.io docker-compose-v2 -y
                    sudo usermod -aG docker $USER && newgrp docker
                    export DOCKERHUB_USERNAME1=${{ vars.DOCKERHUB_USER1 }}
                    export DOCKERHUB_TAG=${{ github.event.workflow_run.head_sha }}
                    echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
                    cd ~devops docker compose up -d --build --force-recreate --pull always
                        