# This will deploy the safe / secure/ tested app to the server.
name: Deploy To Server

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: ssh to prod server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.PROD_SERVER_HOST }}
                username: ${{ secrets.PROD_SERVER_USER }}
                key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                port: 22
                script: |
                    echo "Starting Deployment...."
                    mkdir -p devops                 