name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME1: ${{ vars.DOCKERHUB_USER1 }}
      DOCKERHUB_TAG: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: pull latest image
        run: docker pull $DOCKERHUB_USERNAME1/github-actions-app:latest

      - name: deploy with docker compose
        run: docker compose down && docker compose up -d --build --force-recreate