name: DevsecOps End To End Pipeline

on:
    workflow_dispatch:

jobs:
    # CI (Continuous Integration with security checks
    code-quality:
        uses: ./.github/workflows/code-quality.yml
    
    secret-scan:
        needs: code-quality
        uses: ./.github/workflows/secrets-scan.yml
        
    dependency-scan:
        needs: secret-scan
        uses: ./.github/workflows/dependency-scan.yml
        
    docker-lint:
        needs: dependency-scan
        uses: ./.github/workflows/docker-lint.yml 
    # Builds once security scans are completed.
    build:
        needs: [code-quality, secret-scan, dependency-scan, docker-lint]
        uses: ./.github/workflows/docker-build-push.yml
            