name: Hello workflow

on:
  push:
    branches: [main]    

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello"

      - name: say hello to username
        run: echo "hello $USER"
  
