name: Hello workflow
# runs on a trigger
on:
  push:
    branches: [main]
# this is name of the job
jobs:
  greet:
  # github runner, each job runs on runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello"

      - name: say hello to username
        run: echo "hello $USER"
  details:
    run-on: ubuntu-latest
    steps:
      - name: show what is the version of python, docker, etc
        run: docker --version && python --version     
        
  
