# uses Trivy image scanner for common vulnerabilities 
name: Image Scanner

on: 
    workflow_call:

jobs:
    image-scanner:
        runs-on: ubuntu-latest
        steps:
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                    username: ${{ vars.DOCKERHUB_USER1 }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Trivy image scan              
              uses: aquasecurity/trivy-action@v0.33.1
              with:
                severity-threshold: 'CRITICAL'
                exit-code: '1'
                image-ref: ${{ vars.DOCKERHUB_USER1 }}/github-actions-app:latest

